#!/bin/sh

sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt-get install gdebi

gdebi teamviewer_10*i386.deb

sudo apt-get -f install

# Download links:
# https://download.teamviewer.com/download/teamviewer_i386.deb
